project:
  type: website
  output-dir: docs

website:
  title: "MIT & CfA | Laboratory Astrophysics & Astrochemistry"
  favicon: files/coronene_icon.png
  description: "Gabi Wenzel is a laboratory astrophysicist at MIT & CfA | Harvard & Smithsonian exploring interstellar PAHs, their role in astrochemistry, and bridging the gap between the lab and outer space."
  google-analytics: "G-9VDJND9X2T"
  reader-mode: true
  twitter-card:
    site: "@gbwnzl"
  site-url: https://gbwnzl.github.io/
  repo-url: https://github.com/gbwnzl/gbwnzl.github.io
  repo-actions: [edit, source, issue]

  navbar:
    background: $blueviolet
    title: false
    logo: files/coronene_icon.png
    logo-alt: "Coronene"
    left:
      - href: index.qmd
        text: About
      - href: cv/index.qmd
        text: CV
      - href: publications/index.qmd
        text: Publications
      - href: news/index.qmd
        text: News
    right: 
      - icon: github
        href: https://github.com/gbwnzl
        target: _blank
      # - icon: rss
        # href: news/index.xml
        # - python/index.qmd
        # - accord.qmd

  page-footer:
    background: $dark
    left: © Gabi Wenzel
    right: This website is built with [{{< fa brands github title="GitHub" >}}](https://github.com/gbwnzl){target=_blank}, <a href="https://code.visualstudio.com/"><img src="VSCode_icon.svg" alt="VS Code" style="width:18px;height:18px;"></a>, and [Quarto](https://quarto.org/){target=_blank}.

format:
  html:
    theme:
      light: [cosmo, light.scss]
      dark: [cosmo, dark.scss]
    css: styles.css
    toc: true