project:
  type: website
  output-dir: docs

website:
  title: "gbwnzl"
  favicon: files/coronene_icon.png
  google-analytics: "UA-XXXXXXXX"
  reader-mode: true
  twitter-card: true
  repo-url: https://github.com/gbwnzl/gbwnzl.github.io
  repo-actions: [edit, source, issue]

  navbar:
    background: $blueviolet
    title: false
    logo: files/coronene_icon.png
    logo-alt: "Coronene"
    left:
      - href: index.qmd
        text: About
      - href: cv/index.qmd
        text: CV
      - href: publications/index.qmd
        text: Publications
    right: 
    - icon: github
      href: https://github.com/gbwnzl
      target: _blank
      # - python/index.qmd
      # - accord.qmd
      
  page-footer:
    background: $dark
    left: © Gabi Wenzel
    right: This website is built with [{{< fa brands github title="GitHub" >}}](https://github.com/gbwnzl){target=_blank}, <a href="https://code.visualstudio.com/"><img src="VSCode_icon.svg" alt="VS Code" style="width:18px;height:18px;"></a>, and [Quarto](https://quarto.org/){target=_blank}.


format:
  html:
    theme:
      light: [cosmo, light.scss]
      dark: [cosmo, dark.scss]
    css: styles.css
    toc: true